class_name ItemIcons
extends RefCounted
## Finds the icon for an item base in assets/icons/, in this order:
## 1. the base's `icon` field in bases.json, if set;
## 2. a file named after the base id (e.g. rusted_hatchet.svg or .png), so
##    hand-made art for one base drops straight in;
## 3. the icon for its type: <axe|sword|mace>_<1h|2h>, shield_<defence>,
##    <chest|helm|gloves|boots>_<defence>, ring, amulet, charm_<kind>, or the
##    currency / gem id itself;
## 4. "unknown".
## Defence is str, dex, int or a hybrid like str_int (see GearModels.defence_kind).
## Icons are regenerated by tools/gen_icons.gd.

const DIR: String = "res://assets/icons/"
const EXTENSIONS: Array[String] = ["svg", "png"]

static var _ids: Dictionary = {}
static var _textures: Dictionary = {}


static func texture_for(item: Item) -> Texture2D:
	return texture_for_base(item.base) if item != null else null


static func texture_for_base(base: ItemBase) -> Texture2D:
	var id: String = icon_id(base)
	if not _textures.has(id):
		_textures[id] = _load(id)
	return _textures[id]


## The icon id (file name without extension) used for `base`.
static func icon_id(base: ItemBase) -> String:
	if _ids.has(base.id):
		return _ids[base.id]
	var id: String = "unknown"
	for candidate: String in [base.icon, String(base.id), type_icon(base)]:
		if candidate != "" and _exists(candidate):
			id = candidate
			break
	_ids[base.id] = id
	return id


## The generic icon id for the base's slot, type and tags.
static func type_icon(base: ItemBase) -> String:
	if base.is_weapon():
		for kind: String in ["axe", "sword", "mace"]:
			if base.has_tag(StringName(kind)):
				return "%s_%s" % [kind, "2h" if base.is_two_handed() else "1h"]
		return "sword_1h"
	var defence: String = GearModels.defence_kind(base)
	match base.slot:
		&"off_hand":
			return "shield_" + (defence if defence != "" else "str")
		&"chest", &"helm", &"gloves", &"boots":
			return "%s_%s" % [base.slot, defence if defence != "" else "str"]
		&"ring", &"amulet":
			return String(base.slot)
		&"charm":
			for tag: StringName in base.tags:
				if String(tag).ends_with("_charm"):
					return "charm_" + String(tag).trim_suffix("_charm")
	return String(base.id)


## Where to draw an icon of `icon_size` inside `rect`: centred, keeping its
## aspect ratio, with `pad` pixels of margin.
static func fit(icon_size: Vector2, rect: Rect2, pad: float = 3.0) -> Rect2:
	var area: Rect2 = rect.grow(-pad)
	var scale: float = minf(area.size.x / icon_size.x, area.size.y / icon_size.y)
	var drawn: Vector2 = icon_size * scale
	return Rect2(area.position + (area.size - drawn) * 0.5, drawn)


static func _exists(id: String) -> bool:
	for ext: String in EXTENSIONS:
		if ResourceLoader.exists("%s%s.%s" % [DIR, id, ext]):
			return true
	return false


static func _load(id: String) -> Texture2D:
	for ext: String in EXTENSIONS:
		var path: String = "%s%s.%s" % [DIR, id, ext]
		if ResourceLoader.exists(path):
			return load(path) as Texture2D
	return null
