extends Node
## Sound for the whole game (autoload "Audio").
## - Buses: Master, Music, SFX and Ambience (see default_bus_layout.tres).
## - Music and ambience loops crossfade when the zone changes; the ids come
##   from the zone's Biome (or its AreaInfo override).
## - play() fires a sound effect by id, positional (pooled AudioStreamPlayer3D)
##   or global, with a little random pitch variation. Ids with numbered files
##   (swing_1.wav, swing_2.wav...) pick a variant at random.
## - Sounds hook themselves up: every node added to the tree is checked, and
##   the components that make noise (MeleeAttack, Health, Defenses, GroundItem,
##   ItemPickup, PotionBelt, SkillBar, VendorScreen, InventoryScreen, Game and
##   the player's CharacterAnimator) get their signals connected here, so no
##   scene needs audio nodes.
## - The listener follows the player (facing like the camera), so nearby sounds
##   are loud and distant ones fade.
## Sounds are generated by tools/gen_audio.gd.

const SFX_DIR: String = "res://assets/audio/sfx/"
const MUSIC_DIR: String = "res://assets/audio/music/"
const AMBIENCE_DIR: String = "res://assets/audio/ambience/"
## Default bus volumes: music sits well under the effects.
const BUSES: Dictionary = {&"Music": -3.0, &"SFX": -2.0, &"Ambience": -12.0}
const POOL_3D: int = 16
const POOL_2D: int = 8
const FADE_TIME: float = 2.5
const SILENT_DB: float = -60.0
const MAX_DISTANCE: float = 40.0

var current_music: StringName = &""
var current_ambience: StringName = &""
## "sand" or "dirt": footstep sounds for the current zone.
var footstep_surface: String = "dirt"

## id -> Array of AudioStream variants.
var _sounds: Dictionary = {}
var _pool_3d: Array[AudioStreamPlayer3D] = []
var _pool_2d: Array[AudioStreamPlayer] = []
var _next_3d: int = 0
var _next_2d: int = 0
var _music: Array[AudioStreamPlayer] = []
var _ambience: Array[AudioStreamPlayer] = []
var _music_slot: int = 0
var _ambience_slot: int = 0
var _listener: AudioListener3D
## id -> time (msec) before which the sound won't repeat.
var _cooldown_until: Dictionary = {}
var _had_zone: bool = false
## Headless runs (tests) set up every stream but never start playback,
## since nothing can hear it and live playbacks would outlive a quick quit.
var _silent: bool = DisplayServer.get_name() == "headless"


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_ensure_buses()
	_index_sounds()
	for i: int in POOL_3D:
		var p := AudioStreamPlayer3D.new()
		p.bus = &"SFX"
		p.unit_size = 7.0
		p.max_distance = MAX_DISTANCE
		p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		p.panning_strength = 0.6
		add_child(p)
		_pool_3d.append(p)
	for i: int in POOL_2D:
		var p := AudioStreamPlayer.new()
		p.bus = &"SFX"
		add_child(p)
		_pool_2d.append(p)
	for list: Array in [_music, _ambience]:
		for i: int in 2:
			var p := AudioStreamPlayer.new()
			p.bus = &"Music" if list == _music else &"Ambience"
			p.volume_db = SILENT_DB
			add_child(p)
			list.append(p)
	_listener = AudioListener3D.new()
	add_child(_listener)
	get_tree().node_added.connect(_on_node_added)


func _exit_tree() -> void:
	# Let go of every stream so nothing is left in use at exit.
	for child: Node in get_children():
		if child is AudioStreamPlayer or child is AudioStreamPlayer3D:
			child.call(&"stop")
			child.set(&"stream", null)
	_sounds.clear()


func _process(_delta: float) -> void:
	var player: Node3D = get_tree().get_first_node_in_group("player") as Node3D
	var camera: Camera3D = get_viewport().get_camera_3d()
	if player != null and player.is_inside_tree() and camera != null:
		_listener.global_transform = Transform3D(camera.global_basis, player.global_position + Vector3.UP * 1.6)
		if not _listener.is_current():
			_listener.make_current()


# --- Public API. ---

## Plays sound `id`. Pass a position for a 3D sound, or null for a global one.
func play(id: StringName, at: Variant = null, volume_db: float = 0.0, pitch_variation: float = 0.08) -> Node:
	var stream: AudioStream = _pick(id)
	if stream == null:
		return null
	var pitch: float = 1.0 + randf_range(-pitch_variation, pitch_variation)
	if at is Vector3:
		var p3: AudioStreamPlayer3D = _pool_3d[_next_3d]
		_next_3d = (_next_3d + 1) % POOL_3D
		p3.stream = stream
		p3.global_position = at
		p3.volume_db = volume_db
		p3.pitch_scale = pitch
		if not _silent:
			p3.play()
		return p3
	var p2: AudioStreamPlayer = _pool_2d[_next_2d]
	_next_2d = (_next_2d + 1) % POOL_2D
	p2.stream = stream
	p2.volume_db = volume_db
	p2.pitch_scale = pitch
	if not _silent:
		p2.play()
	return p2


## Like play(), but skipped if the same sound played less than `interval` seconds ago.
func play_limited(id: StringName, at: Variant, interval: float, volume_db: float = 0.0) -> Node:
	var now: int = Time.get_ticks_msec()
	if now < _cooldown_until.get(id, 0):
		return null
	_cooldown_until[id] = now + int(interval * 1000.0)
	return play(id, at, volume_db)


## True if there is a sound with this id.
func has_sound(id: StringName) -> bool:
	return _sounds.has(id)


func sound_ids() -> Array:
	return _sounds.keys()


## Crossfades to music track `id` (a file in assets/audio/music/). Empty stops the music.
func play_music(id: StringName) -> void:
	if id == current_music:
		return
	current_music = id
	_music_slot = _crossfade(_music, _music_slot, MUSIC_DIR, id)


## Crossfades to ambience loop `id` (a file in assets/audio/ambience/).
func play_ambience(id: StringName) -> void:
	if id == current_ambience:
		return
	current_ambience = id
	_ambience_slot = _crossfade(_ambience, _ambience_slot, AMBIENCE_DIR, id)


## The loop streams for an id, or null (tests use this).
func load_loop(dir: String, id: StringName) -> AudioStream:
	var path: String = "%s%s.wav" % [dir, id]
	if id == &"" or not ResourceLoader.exists(path):
		return null
	var stream: AudioStream = load(path)
	var wav: AudioStreamWAV = stream as AudioStreamWAV
	if wav != null and wav.loop_mode == AudioStreamWAV.LOOP_DISABLED:
		wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wav.loop_begin = 0
		wav.loop_end = int(wav.get_length() * wav.mix_rate)
	return stream


# --- Setup. ---

func _ensure_buses() -> void:
	for bus: StringName in BUSES:
		if AudioServer.get_bus_index(bus) < 0:
			AudioServer.add_bus()
			var index: int = AudioServer.bus_count - 1
			AudioServer.set_bus_name(index, bus)
			AudioServer.set_bus_send(index, &"Master")
			AudioServer.set_bus_volume_db(index, BUSES[bus])


## Finds every effect in assets/audio/sfx/, grouping numbered variants.
func _index_sounds() -> void:
	var files: PackedStringArray = ResourceLoader.list_directory(SFX_DIR)
	for f: String in files:
		if not f.ends_with(".wav"):
			continue
		var base: String = f.get_basename()
		var parts: PackedStringArray = base.rsplit("_", true, 1)
		var id: String = parts[0] if parts.size() == 2 and parts[1].is_valid_int() else base
		if not _sounds.has(StringName(id)):
			_sounds[StringName(id)] = []
		(_sounds[StringName(id)] as Array).append(SFX_DIR + f)


func _pick(id: StringName) -> AudioStream:
	var variants: Array = _sounds.get(id, [])
	if variants.is_empty():
		return null
	var i: int = randi_range(0, variants.size() - 1)
	if variants[i] is String:
		variants[i] = load(variants[i])
	return variants[i]


func _crossfade(players: Array, slot: int, dir: String, id: StringName) -> int:
	var old: AudioStreamPlayer = players[slot]
	var next_slot: int = 1 - slot
	var fresh: AudioStreamPlayer = players[next_slot]
	if old.playing:
		var fade_out: Tween = create_tween()
		fade_out.tween_property(old, "volume_db", SILENT_DB, FADE_TIME)
		fade_out.tween_callback(old.stop)
	var stream: AudioStream = load_loop(dir, id)
	if stream == null:
		return slot
	fresh.stream = stream
	fresh.volume_db = SILENT_DB
	if not _silent:
		fresh.play()
	create_tween().tween_property(fresh, "volume_db", 0.0, FADE_TIME).set_trans(Tween.TRANS_SINE)
	return next_slot


# --- Hooks. ---

func _on_node_added(node: Node) -> void:
	if node is Game:
		(node as Game).zone_changed.connect(_on_zone_changed)
	elif node is MeleeAttack:
		var melee: MeleeAttack = node as MeleeAttack
		melee.swing_started.connect(func() -> void: play(&"swing", _position_of(melee), -4.0, 0.12))
		melee.swing_hit.connect(_on_swing_hit)
	elif node is Health:
		var health: Health = node as Health
		health.damaged.connect(func(_amount: float) -> void: _on_damaged(health))
		health.died.connect(func() -> void: _on_died(health))
	elif node is Defenses:
		var defenses: Defenses = node as Defenses
		defenses.avoided.connect(func(how: String) -> void:
			play(&"block" if how == "Block" else &"evade", _position_of(defenses), -2.0))
	elif node is GroundItem:
		_on_item_dropped.call_deferred(node)
	elif node is ItemPickup:
		(node as ItemPickup).picked_up.connect(func(_item: Item) -> void: play(&"pickup", null, -3.0))
	elif node is PotionBelt:
		(node as PotionBelt).drank.connect(func(_index: int) -> void: play(&"potion_drink", null, -2.0))
	elif node is SkillBar:
		(node as SkillBar).use_failed.connect(func(_reason: String) -> void: play_limited(&"skill_fail", null, 0.4, -6.0))
	elif node is VendorScreen:
		var shop: VendorScreen = node as VendorScreen
		shop.bought.connect(func(_item: Item) -> void: play(&"vendor_buy", null, -2.0))
		shop.sold.connect(func(_item: Item) -> void: play(&"vendor_sell", null, -2.0))
	elif node is InventoryScreen:
		var screen: InventoryScreen = node as InventoryScreen
		# Skip the hide that happens while the UI is being set up.
		screen.visibility_changed.connect(func() -> void:
			if _had_zone:
				play(&"inventory_open" if screen.visible else &"inventory_close", null, -4.0, 0.03))
	elif node is CharacterAnimator and node.get_parent() != null and node.get_parent().is_in_group("player"):
		var animator: CharacterAnimator = node as CharacterAnimator
		animator.footstep.connect(func() -> void:
			play(StringName("footstep_" + footstep_surface), _position_of(animator), -13.0, 0.12))


func _position_of(component: Node) -> Variant:
	var body: Node3D = component.get_parent() as Node3D
	return body.global_position + Vector3.UP if body != null and body.is_inside_tree() else null


func _on_zone_changed(zone: Node3D) -> void:
	if _had_zone:
		play(&"zone_travel", null, -3.0, 0.02)
	_had_zone = true
	var info: AreaInfo = zone.get_node_or_null("AreaInfo") as AreaInfo
	var town: bool = info != null and info.is_town
	var music: StringName = &""
	var ambience: StringName = &""
	if zone is Zone:
		music = (zone as Zone).music_id()
		ambience = (zone as Zone).ambience_id()
	elif info != null:
		music = info.music_id
		ambience = info.ambience_id
	if music == &"":
		music = &"town" if town else &"shore"
	if ambience == &"":
		ambience = &"campfire" if town else &"sea"
	footstep_surface = "sand" if ambience == &"sea" else "dirt"
	play_music(music)
	play_ambience(ambience)


func _on_swing_hit(target: Node3D, _damage: float, critical: bool) -> void:
	if not is_instance_valid(target):
		return
	var at: Vector3 = target.global_position + Vector3.UP
	if critical:
		play(&"crit", at, 0.0, 0.05)
		return
	var defenses: Defenses = target.get_node_or_null("Defenses") as Defenses
	play(&"hit_armour" if defenses != null and defenses.armour > 0.0 else &"hit_flesh", at, -1.0, 0.1)


func _on_damaged(health: Health) -> void:
	var body: Node = health.get_parent()
	if body.is_in_group("player"):
		play_limited(&"player_hurt", _position_of(health), 0.5, -3.0)
	elif body.is_in_group("enemies") and randf() < 0.45:
		play_limited(&"goblin_grunt", _position_of(health), 0.25, -4.0)


func _on_died(health: Health) -> void:
	var body: Node = health.get_parent()
	if body.is_in_group("player"):
		play(&"player_death", _position_of(health), 0.0, 0.0)
	elif body.is_in_group("enemies"):
		play(&"goblin_death", _position_of(health), -2.0)


func _on_item_dropped(ground: GroundItem) -> void:
	if not is_instance_valid(ground) or not ground.is_inside_tree():
		return
	var item: Item = ground.item
	var id: StringName = &"drop_normal"
	if item.base.is_currency():
		id = &"orb_drop"
	elif not item.base.is_gem():
		id = [&"drop_normal", &"drop_magic", &"drop_rare", &"drop_legendary"][item.rarity]
	play(id, ground.global_position, -2.0 if item.rarity < Item.Rarity.RARE else 1.0, 0.04)
